options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/samaanai-streamlit:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/samaanai-streamlit:$COMMIT_SHA']

  # Deploy the container image to Cloud Run (Initial Deployment ONLY)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'samaanai-streamlit',  # Your service name
        '--image', 'gcr.io/$PROJECT_ID/samaanai-streamlit:$COMMIT_SHA',
        '--region', '$_REGION',  # Use the substitution variable
        '--platform', 'managed',
        '--allow-unauthenticated', # Or configure authentication as needed
        '--set-secrets',  # Connect to Secret Manager for the password
        'DB_PASSWORD=DB_PASSWORD:latest'

      ]
images:
  - 'gcr.io/$PROJECT_ID/samaanai-streamlit:$COMMIT_SHA'