services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-samaanai-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  # Changed: Build context is now the root directory
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-samaanai-db}       # Corrected default
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      - db
    volumes:
      - .:/app  # Changed: Mount the root directory
    env_file:
      - .env

volumes:
  postgres_data: